### ISSUE TITLE
Error gt_ind does not exist

### ISSUE THREAD

**Issue by david-castillo** [gimelbrantlab/ASEReadCounter_star#3]
Hello,

I might be the only one using that part of the code, but just to warn you there's an error in this line of the code:

https://github.com/gimelbrantlab/ASEReadCounter_star/blob/48ff1a67c8f925bd65396081bf33e4055306cd4c/python3/prepare_reference.py#L125

gt_ind does not exist, you probably want to replace it by gt_name

Regards

David

**Comment by Strausyatina** [comment]
Hello David,

thank you a lot for your contribution! Now it is fixed.

Best,
Asia
